INSERT INTO "Roles" VALUES(1, 'RATER', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Roles" VALUES(2, 'PROSPECT', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Roles" VALUES(3, 'STAFF', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Roles" VALUES(4, 'ADMIN', LOCALTIMESTAMP, LOCALTIMESTAMP);

INSERT INTO "Levels" VALUES(1, 'L1', 3, 60, 'Licence 1', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(2, 'L2', 3, 120, 'Licence 2', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(3, 'L3', 2, 180, 'Licence 3', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(4, 'M1', 2, 240, 'Master 1', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(5, 'M2', 1, 300, 'Master 2', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(6, 'D1', 1, 300, 'Doctorat 1', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(7, 'D2', 1, 300, 'Doctorat 2', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(8, 'D3', 1, 300, 'Doctorat 3', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(9, 'BAC', 4, 0, 'Bac', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(10, 'CAP', 4, 0, 'CAP, BEP', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(11, 'BTS', 3, 120, 'BTS', LOCALTIMESTAMP, LOCALTIMESTAMP);
INSERT INTO "Levels" VALUES(12, 'DUT', 3, 120, 'DUT', LOCALTIMESTAMP, LOCALTIMESTAMP);


